declare const config: {
    width: number;
    height: number;
    useContentSize: boolean;
    center: boolean;
    minWidth: number;
    minHeight: number;
    maxWidth: number;
    maxHeight: number;
    resizable: boolean;
    alwaysOnTop: boolean;
    fullscreen: boolean;
    skipTaskbar: boolean;
    kiosk: boolean;
    title: string;
    icon: string | undefined;
    show: boolean;
    frame: boolean;
    acceptFirstMouse: boolean;
    disableAutoHideCursor: boolean;
    autoHideMenuBar: boolean;
    enableLargerThanScreen: boolean;
    backgroundColor: string;
    darkTheme: boolean;
    transparent: boolean;
    titleBarStyle?: 'default' | 'hidden' | 'hiddenInset' | 'customButtonsOnHover';
    webPreferences: {
        nodeIntegration: boolean;
        preload: string;
        partition: string | undefined;
        zoomFactor: number;
        javascript: boolean;
        webSecurity: boolean;
        allowDisplayingInsecureContent: boolean;
        allowRunningInsecureContent: boolean;
        images: boolean;
        java: boolean;
        textAreasAreResizable: boolean;
        webgl: boolean;
        webaudio: boolean;
        plugins: boolean;
        experimentalFeatures: boolean;
        experimentalCanvasFeatures: boolean;
        overlayScrollbars: boolean;
        overlayFullscreenVideo: boolean;
        sharedWorker: boolean;
        directWrite: boolean;
        pageVisibility: boolean;
    };
};
export default config;
